services:
  - type: web
    name: liberation-backend
    runtime: node
    plan: free
    rootDir: apps/backend
    buildCommand: npm ci && npx prisma generate && npm run build
    startCommand: npx prisma migrate deploy && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3005
      - key: DATABASE_URL
        fromDatabase:
          name: liberation-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: LIVEKIT_URL
        value: wss://liberation-5xb6iqb6.livekit.cloud
      - key: LIVEKIT_API_KEY
        value: APIUGbq3Qbv77v6
      - key: LIVEKIT_API_SECRET
        value: upLIe2r0C02psSSzb8C4H44oXgfu5ejM3n7e4frMuiyH
      - key: FRONTEND_URL
        sync: false

databases:
  - name: liberation-db
    plan: free
    databaseName: ta7aror
